"use client";
import { useEffect,useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Response={name:string;seats:number;status:"pending"|"yes"|"no";attendees:number};
export default function RSVPForm(){
  const [code,setCode]=useState(""),[guest,setGuest]=useState<Response|null>(null),[status,setStatus]=useState<"yes"|"no">("yes"),[attendees,setAttendees]=useState(1),[message,setMessage]=useState(""),[error,setError]=useState(false),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
  useEffect(()=>{const c=new URLSearchParams(location.search).get("code");if(c){setCode(c);void lookup(c);}},[]);
  async function lookup(c:string){setBusy(true);setMessage("");setSaved(false);try{const r=await fetch(`/api/rsvp?code=${encodeURIComponent(c.trim())}`,{cache:"no-store"});const d=await r.json() as {error?:string;guest:Response};if(!r.ok)throw Error(d.error);setGuest(d.guest);setStatus(d.guest.status==="no"?"no":"yes");setAttendees(d.guest.status==="yes"?d.guest.attendees:1);}catch(e){setGuest(null);setMessage(e instanceof Error?e.message:"Invitation not found");setError(true);}finally{setBusy(false);}}
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/rsvp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code,status,attendees:status==="yes"?attendees:0})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setSaved(true);setError(false);setMessage(status==="yes"?"Thank you! Your attendance is confirmed.":"Thank you for letting us know. We’ll miss you.");}catch(e){setError(true);setMessage(e instanceof Error?e.message:"Could not save your reply");}finally{setBusy(false);}}
  return <section className="rsvp-page"><section className="rsvp-card"><div className="kicker">Cindy & Dorbor</div><h1>Kindly reply</h1><p>Traditional wedding · 30 January 2027 · 4:00 pm<br/>Ellenbrook Community Centre Function Hall</p><div className="field"><label htmlFor="invite-code">Your personal invitation code</label><Input id="invite-code" autoComplete="off" value={code} onChange={e=>setCode(e.target.value)} placeholder="Paste your code here"/></div>{!guest?<Button disabled={busy||!code.trim()} onClick={()=>void lookup(code)} className="rsvp-submit">{busy?"Checking…":"Find invitation"}</Button>:<form onSubmit={submit}><p><strong>{guest.name}</strong><br/>Reserved places: {guest.seats}</p><fieldset style={{border:0,padding:0,margin:"20px 0"}}><legend style={{textAlign:"left",fontWeight:700}}>Will you attend?</legend><label className="rsvp-option"><input type="radio" name="reply" checked={status==="yes"} onChange={()=>setStatus("yes")}/>Joyfully accept</label><label className="rsvp-option"><input type="radio" name="reply" checked={status==="no"} onChange={()=>setStatus("no")}/>Regretfully decline</label></fieldset>{status==="yes"&&<div className="field"><label htmlFor="attendees">Number attending (maximum {guest.seats})</label><Input id="attendees" type="number" min={1} max={guest.seats} value={attendees} onChange={e=>setAttendees(Number(e.target.value))} required/></div>}<Button className="rsvp-submit" type="submit" disabled={busy}>{busy?"Saving…":saved?"Update response":"Send response"}</Button><p className="subtle">You can use this same link to update your reply.</p></form>}{message&&<div className={error?"error-box":"success-box"} role="status">{message}</div>}<p className="subtle" style={{fontSize:14,marginTop:25}}>Please reply by 28 November 2026.</p></section></section>;
}
