"use client";
import { useEffect,useMemo,useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
import type { Guest } from "@/lib/guests";

type Filter="all"|"yes"|"pending"|"no";
export default function Dashboard() {
  const [guests,setGuests]=useState<Guest[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(false);
  const [name,setName]=useState(""),[seats,setSeats]=useState(1),[query,setQuery]=useState(""),[filter,setFilter]=useState<Filter>("all"),[editing,setEditing]=useState<string|null>(null),[editName,setEditName]=useState(""),[editSeats,setEditSeats]=useState(1);
  function flash(text:string,isError=false){setMessage(text);setError(isError);}
  useEffect(()=>{let cancelled=false;async function loadGuests(){try{const r=await fetch("/api/admin/guests",{cache:"no-store"});const data=await r.json() as {error?:string;guests:Guest[]};if(!r.ok)throw Error(data.error);if(!cancelled)setGuests(data.guests);}catch(e){if(!cancelled){setMessage(e instanceof Error?e.message:"Could not load guests");setError(true);}}finally{if(!cancelled)setLoading(false);}}void loadGuests();return()=>{cancelled=true;};},[]);
  async function add(e:React.FormEvent){e.preventDefault();setBusy(true);flash("");try{const r=await fetch("/api/admin/guests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,seats})});const d=await r.json() as {error?:string;guest:Guest};if(!r.ok)throw Error(d.error);setGuests(g=>[...g,d.guest].sort((a,b)=>a.name.localeCompare(b.name)));setName("");setSeats(1);flash(`Invitation created for ${d.guest.name}. Copy their personal RSVP link below.`);}catch(e){flash(e instanceof Error?e.message:"Could not add guest",true);}finally{setBusy(false);}}
  async function update(guest:Guest,change:Record<string,unknown>){setBusy(true);flash("");try{const r=await fetch(`/api/admin/guests/${encodeURIComponent(guest.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(change)});const d=await r.json() as {error?:string;guest:Guest};if(!r.ok)throw Error(d.error);setGuests(list=>list.map(g=>g.id===guest.id?d.guest:g).sort((a,b)=>a.name.localeCompare(b.name)));setEditing(null);flash("Guest updated.");}catch(e){flash(e instanceof Error?e.message:"Could not update guest",true);}finally{setBusy(false);}}
  function startEdit(g:Guest){setEditing(g.id);setEditName(g.name);setEditSeats(g.seats);}
  async function copyLink(g:Guest){try{await navigator.clipboard.writeText(`${location.origin}/rsvp?code=${g.code}`);flash(`Personal RSVP link copied for ${g.name}.`);}catch{flash("Copy unavailable. Select the link in the guest row.",true);}}
  const shown=useMemo(()=>guests.filter(g=>(filter==="all"||g.status===filter)&&g.name.toLowerCase().includes(query.trim().toLowerCase())),[guests,filter,query]);
  const yes=guests.filter(g=>g.status==="yes"),pending=guests.filter(g=>g.status==="pending"),no=guests.filter(g=>g.status==="no");
  return <main className="shell">
    <header className="topbar"><div className="brand"><span className="monogram">C&D</span><div><div className="brand-title">Cindy & Dorbor</div><div className="brand-small">Wedding reservations</div></div></div><a className="toplink" href="/rsvp">Guest RSVP page</a></header>
    <div className="intro-row"><div><div className="kicker">Saturday · 30 January 2027</div><h1 className="headline">Guest list</h1><p className="subtle">Add each invited party, copy their private link, and track their response.</p></div></div>
    <div className="metrics" aria-label="Reservation summary"><div className="metric"><p className="metric-label">Invitations</p><p className="metric-number">{guests.length}</p></div><div className="metric"><p className="metric-label">Attending</p><p className="metric-number">{yes.reduce((sum,g)=>sum+g.attendees,0)}</p></div><div className="metric"><p className="metric-label">Awaiting reply</p><p className="metric-number">{pending.length}</p></div><div className="metric"><p className="metric-label">Declined</p><p className="metric-number">{no.length}</p></div></div>
    <div className="stack"><section className="panel" aria-labelledby="add-title"><h2 className="panel-title" id="add-title">Add an invitation</h2><p className="subtle">Set the number of places for this named party. Only someone with their personal link can respond.</p><form onSubmit={add} className="form-grid"><div className="field"><label htmlFor="guest-name">Guest or family name</label><Input id="guest-name" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Janet and family" maxLength={100} required/></div><div className="field"><label htmlFor="guest-seats">Places</label><Input id="guest-seats" type="number" min={1} max={20} value={seats} onChange={e=>setSeats(Number(e.target.value))} required/></div><Button type="submit" disabled={busy}>Add guest</Button></form></section>
    <section className="panel" aria-labelledby="list-title"><div className="list-head"><div><h2 className="panel-title" id="list-title">Invitations</h2><p className="subtle">{shown.length} of {guests.length} shown</p></div><div className="list-tools"><Input className="filter" aria-label="Search guests" placeholder="Search names" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="inline-actions" role="group" aria-label="Filter by response">{(["all","yes","pending","no"] as Filter[]).map(f=><Button key={f} size="sm" variant={filter===f?"default":"outline"} onClick={()=>setFilter(f)}>{({all:"All",yes:"Attending",pending:"Awaiting",no:"Declined"})[f]}</Button>)}</div>
      <p className={`feedback ${error?"error":""}`} role="status">{message}</p>
      {loading?<p className="empty">Loading guests…</p>:shown.length===0?<p className="empty">{guests.length===0?"No invitations yet. Add your first guest above.":"No guests match this view."}</p>:<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Guest</TableHead><TableHead>Places</TableHead><TableHead>Response</TableHead><TableHead>Attending</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{shown.map(g=><TableRow key={g.id}><TableCell>{editing===g.id?<div className="edit-grid"><Input aria-label="Edit guest name" value={editName} maxLength={100} onChange={e=>setEditName(e.target.value)}/><Input aria-label="Edit places" type="number" min={1} max={20} value={editSeats} onChange={e=>setEditSeats(Number(e.target.value))}/></div>:<><div className="guest-name">{g.name}</div><div className="code">Code: {g.code.slice(0,8)}…</div></>}</TableCell><TableCell>{g.seats}</TableCell><TableCell><span className={`pill ${g.status}`}>{g.status==="yes"?"Attending":g.status==="no"?"Declined":"Awaiting"}</span></TableCell><TableCell>{g.attendees}</TableCell><TableCell><div className="inline-actions">{editing===g.id?<><button className="small-btn" disabled={busy} onClick={()=>void update(g,{name:editName,seats:editSeats,attendees:g.status==="yes"?Math.min(g.attendees,editSeats):0})}>Save</button><button className="small-btn" onClick={()=>setEditing(null)}>Cancel</button></>:<><button className="small-btn" onClick={()=>void copyLink(g)}>Copy RSVP link</button><button className="small-btn" onClick={()=>startEdit(g)}>Edit</button><button className="small-btn" disabled={busy} onClick={()=>void update(g,{status:g.status==="yes"?"pending":"yes",attendees:g.status==="yes"?0:1})}>{g.status==="yes"?"Reset":"Mark attending"}</button><button className="small-btn" disabled={busy} onClick={()=>void update(g,{status:"no",attendees:0})}>Declined</button></>}</div></TableCell></TableRow>)}</TableBody></Table></div>}
    </section></div>
  </main>;
}
